-- 1. Tabela VAGAS Tabela de Origem 1
CREATE TABLE  VAGAS (
    ID_VAGA INT NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    EMPRESA VARCHAR(100) NOT NULL,
    SALARIO DECIMAL NOT NULL,
    PRIMARY KEY (ID_VAGA)
);

-- 2. Tabela CANDIDATAS Tabela de Origem 2
CREATE TABLE CANDIDATAS (
    ID_CANDIDATA INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_CANDIDATA)
);

-- 3. Tabela CANDIDATURAS Tabela Associativa/Ligação) 
CREATE TABLE CANDIDATURAS (
    ID_CANDIDATURA INT NOT NULL,
    DATA_ENVIO DATETIME NOT NULL,    
    ID_VAGA INT,
    ID_CANDIDATA INT,
    PRIMARY KEY (ID_CANDIDATURA),
    FOREIGN KEY (ID_VAGA) REFERENCES VAGAS(ID_VAGA),
    FOREIGN KEY (ID_CANDIDATA) REFERENCES CANDIDATAS(ID_CANDIDATA)
);
